<script setup lang="ts">
import { computed,onMounted,reactive,ref } from 'vue'
import { useRoute } from 'vue-router'
import Button from 'primevue/button'
import InputText from 'primevue/inputtext'
import Textarea from 'primevue/textarea'
import Select from 'primevue/select'
import Dialog from 'primevue/dialog'
import Tag from 'primevue/tag'
import Message from 'primevue/message'
import { useToast } from 'primevue/usetoast'
import { useTecnologiaStore } from '@/stores/tecnologia.store'
import { statuses,types,type TicketInput,type Activity,type Status } from '@/types/tecnologia'
const store=useTecnologiaStore(),route=useRoute(),toast=useToast()
const section=computed(()=>route.params.section),query=ref(''),origin=ref('Todos'),status=ref('Todos'),createOpen=ref(false),generalOpen=ref(false),selectedId=ref<string|null>(null),busy=ref(false)
const selected=computed(()=>store.data.tickets.find(t=>t.id===selectedId.value))
const detailOpen=computed({get:()=>!!selected.value,set:(v:boolean)=>{if(!v){selectedId.value=null;note.value=''}}})
const emptyForm=():TicketInput=>({title:'',description:'',type:'Bug',origin:'Interno',priority:'Media',requester:'',assignee:'Por asignar'})
const form=reactive<TicketInput>(emptyForm()),note=ref(''),visibility=ref<Activity['visibility']>('Nota interna'),general=ref('')
const filtered=computed(()=>store.data.tickets.filter(t=>(t.title+' '+t.id+' '+t.requester).toLocaleLowerCase().includes(query.value.toLocaleLowerCase())&&(origin.value==='Todos'||t.origin===origin.value)&&(status.value==='Todos'||t.status===status.value)))
const stats=computed(()=>[{label:'Tickets abiertos',value:store.data.tickets.filter(t=>t.status!=='Resuelto').length,icon:'pi-ticket'},{label:'En proceso',value:store.data.tickets.filter(t=>t.status==='En proceso').length,icon:'pi-code'},{label:'En validación QA',value:store.data.tickets.filter(t=>t.status==='En QA').length,icon:'pi-check-square'},{label:'Resueltos',value:store.data.tickets.filter(t=>t.status==='Resuelto').length,icon:'pi-check-circle'}])
const ticketEvents=computed(()=>store.data.activities.filter(e=>e.ticketId===selectedId.value))
const severity=(s:string)=>s==='Resuelto'?'success':s==='En QA'?'secondary':s==='En proceso'?'warn':'info'
const date=(s:string)=>new Date(s).toLocaleString('es-MX',{dateStyle:'medium',timeStyle:'short'})
async function run(action:()=>Promise<void>){busy.value=true;try{await action();toast.add({severity:'success',summary:'Guardado',life:2200})}catch(e){toast.add({severity:'error',summary:'No se pudo guardar',detail:e instanceof Error?e.message:'Intenta de nuevo',life:6000})}finally{busy.value=false}}
async function create(){if(!form.title.trim()||!form.description.trim()||!form.requester.trim())return;await run(async()=>{await store.create({...form,title:form.title.trim(),description:form.description.trim(),requester:form.requester.trim()});createOpen.value=false;Object.assign(form,emptyForm())})}
async function saveNote(){if(!note.value.trim()||!selected.value)return;await run(async()=>{await store.addActivity({ticketId:selectedId.value,text:note.value.trim(),visibility:visibility.value});note.value=''})}
async function saveGeneral(){if(!general.value.trim())return;await run(async()=>{await store.addActivity({ticketId:null,text:general.value.trim(),visibility:'Nota interna'});general.value='';generalOpen.value=false})}
function changeStatus(value:Status){if(selected.value&&value!==selected.value.status)void run(()=>store.changeStatus(selected.value!.id,value))}
onMounted(()=>store.load())
</script>
<template><div class="page"><div class="page-heading"><div><h1>Tecnología</h1><p>Un espacio para reportar, resolver y dejar constancia.</p></div><Button label="Nuevo ticket" icon="pi pi-plus" :disabled="!store.ready||busy" @click="createOpen=true"/></div>
<Message v-if="store.error" severity="error" :closable="false">{{ store.error }} <Button label="Reintentar" text @click="store.load()"/></Message>
<div class="stats"><div v-for="stat in stats" :key="stat.label" class="stat"><span>{{stat.label}} <i :class="['pi',stat.icon]"/></span><b>{{stat.value}}</b></div></div>
<div class="tabs"><RouterLink to="/tecnologia/tickets">Tickets</RouterLink><RouterLink to="/tecnologia/tablero">Tablero de trabajo</RouterLink><RouterLink to="/tecnologia/bitacora">Bitácora general</RouterLink></div>
<p v-if="store.loading" role="status">Cargando…</p>
<div v-else-if="section==='tickets'" class="tickets-layout"><section class="panel"><div class="panel-heading"><h2>Bandeja de tickets</h2><small>{{filtered.length}} solicitudes</small></div><div class="filters"><InputText v-model="query" aria-label="Buscar tickets" placeholder="Buscar por título, folio o solicitante"/><Select v-model="origin" :options="['Todos','Cliente','Interno']" aria-label="Origen"/><Select v-model="status" :options="['Todos',...statuses]" aria-label="Estado"/></div><div class="table-scroll"><table><thead><tr><th>Ticket / solicitud</th><th>Origen</th><th>Prioridad</th><th>Estado</th></tr></thead><tbody><tr v-for="ticket in filtered" :key="ticket.id"><td><button class="ticket-link" @click="selectedId=ticket.id"><small>{{ticket.id.slice(0,14)}} · {{ticket.type}}</small><strong>{{ticket.title}}</strong><small>{{ticket.requester}} · {{ticket.assignee}}</small></button></td><td><Tag :value="ticket.origin" :severity="ticket.origin==='Cliente'?'info':'secondary'"/></td><td><span :class="['priority',ticket.priority==='Alta'?'high':'']">● {{ticket.priority}}</span></td><td><Tag :value="ticket.status" :severity="severity(ticket.status)"/></td></tr><tr v-if="!filtered.length"><td colspan="4" class="empty">No hay tickets para mostrar.</td></tr></tbody></table></div></section><aside class="panel activity-panel"><div class="panel-heading"><h2>Actividad reciente</h2><i class="pi pi-history"/></div><div class="timeline"><article v-for="event in store.data.activities.slice(0,5)" :key="event.id"><small>{{event.ticketId?.slice(0,14)||'Actividad general'}}</small><p>{{event.text}}</p><small>{{date(event.createdAt)}} · {{event.visibility}}</small></article><p v-if="!store.data.activities.length">Aún no hay actividades.</p></div></aside></div>
<div v-else-if="section==='tablero'" class="board"><section v-for="column in statuses" :key="column" class="board-column"><h2>{{column}} <small>{{store.data.tickets.filter(t=>t.status===column).length}}</small></h2><button v-for="ticket in store.data.tickets.filter(t=>t.status===column)" :key="ticket.id" class="board-card" @click="selectedId=ticket.id"><small>{{ticket.type}} · {{ticket.id.slice(0,14)}}</small><strong>{{ticket.title}}</strong><Tag :value="ticket.origin" severity="secondary"/><p>{{ticket.assignee}} · {{ticket.priority}}</p></button><p v-if="!store.data.tickets.some(t=>t.status===column)" class="empty">Sin tickets</p></section></div>
<section v-else class="panel"><div class="panel-heading"><div><h2>Bitácora general</h2><small>Avances, cambios de estado y actividades del equipo.</small></div><Button label="Registrar actividad" icon="pi pi-plus" :disabled="!store.ready||busy" @click="generalOpen=true"/></div><div class="timeline"><article v-for="event in store.data.activities" :key="event.id"><button v-if="event.ticketId" class="text-link" @click="selectedId=event.ticketId">{{event.ticketId.slice(0,14)}}</button><b v-else>Actividad general</b><p>{{event.text}}</p><small>{{date(event.createdAt)}} · {{event.visibility}}</small></article><p v-if="!store.data.activities.length" class="empty">Registra la primera actividad del equipo.</p></div></section>
<Dialog v-model:visible="createOpen" modal header="Nuevo ticket" :style="{width:'660px'}" :breakpoints="{'700px':'95vw'}"><form @submit.prevent="create"><label for="title">Título</label><InputText id="title" v-model="form.title" required maxlength="140"/><label for="description">Descripción / criterios de aceptación</label><Textarea id="description" v-model="form.description" required rows="4" maxlength="10000"/><div class="form-grid"><div><label for="type">Tipo</label><Select inputId="type" v-model="form.type" :options="[...types]"/></div><div><label for="origin">Origen</label><Select inputId="origin" v-model="form.origin" :options="['Interno','Cliente']"/></div><div><label for="priority">Prioridad</label><Select inputId="priority" v-model="form.priority" :options="['Alta','Media','Baja']"/></div><div><label for="requester">Solicitante</label><InputText id="requester" v-model="form.requester" required maxlength="160"/></div></div><label for="assignee">Responsable</label><InputText id="assignee" v-model="form.assignee" maxlength="160"/><div class="actions"><Button label="Cancelar" severity="secondary" text @click="createOpen=false"/><Button type="submit" label="Crear ticket" :loading="busy"/></div></form></Dialog>
<Dialog v-model:visible="detailOpen" modal :header="selected?.id.slice(0,14)" :style="{width:'740px'}" :breakpoints="{'780px':'95vw'}"><template v-if="selected"><h2>{{selected.title}}</h2><p class="description">{{selected.description}}</p><div class="detail-meta"><Tag :value="selected.origin"/><Tag :value="selected.type" severity="secondary"/><span>{{selected.requester}} · {{selected.assignee}}</span></div><label for="ticket-status">Estado</label><Select inputId="ticket-status" :modelValue="selected.status" :options="[...statuses]" :disabled="busy" @update:modelValue="changeStatus"/><h3>Bitácora del ticket</h3><div class="timeline"><article v-for="event in ticketEvents" :key="event.id"><p>{{event.text}}</p><small>{{date(event.createdAt)}} · {{event.visibility}}</small></article></div><form @submit.prevent="saveNote"><label for="note">Registrar avance o respuesta</label><Textarea id="note" v-model="note" required rows="3" maxlength="10000"/><label for="visibility">Visibilidad prevista</label><Select inputId="visibility" v-model="visibility" :options="['Nota interna','Respuesta al solicitante']"/><small class="hint">Clasificación para el futuro portal de clientes. Esta versión muestra la vista interna.</small><div class="actions"><Button type="submit" label="Guardar actividad" :loading="busy"/></div></form></template></Dialog>
<Dialog v-model:visible="generalOpen" modal header="Registrar actividad general" :style="{width:'560px'}" :breakpoints="{'600px':'95vw'}"><form @submit.prevent="saveGeneral"><label for="general">Actividad realizada</label><Textarea id="general" v-model="general" required rows="5" maxlength="10000" placeholder="Mantenimiento, revisión de equipos, actualización…"/><p>Se guardará como nota interna sin vincularla a un ticket.</p><div class="actions"><Button type="submit" label="Guardar actividad" :loading="busy"/></div></form></Dialog>
</div></template>
