<script setup lang="ts">
import { computed,onMounted,ref } from 'vue'
import { useRoute,useRouter } from 'vue-router'
import Button from 'primevue/button'
import InputText from 'primevue/inputtext'
import Textarea from 'primevue/textarea'
import Select from 'primevue/select'
import Dialog from 'primevue/dialog'
import Tag from 'primevue/tag'
import Message from 'primevue/message'
import { useToast } from 'primevue/usetoast'
import { useTecnologiaStore } from '@/stores/tecnologia.store'
import { statuses,categorias,type Activity,type Status } from '@/types/tecnologia'
const store=useTecnologiaStore(),route=useRoute(),router=useRouter(),toast=useToast()
const section=computed(()=>route.params.section),query=ref(''),categoria=ref('Todos'),status=ref('Todos'),generalOpen=ref(false),selectedId=ref<string|null>(null),busy=ref(false)
const selected=computed(()=>store.data.tickets.find(t=>t.id===selectedId.value))
const detailOpen=computed({get:()=>!!selected.value,set:(v:boolean)=>{if(!v){selectedId.value=null;note.value=''}}})
const note=ref(''),visibility=ref<Activity['visibility']>('Nota interna'),general=ref('')
const filtered=computed(()=>store.data.tickets.filter(t=>(t.title+' '+t.id+' '+t.solicitanteId).toLocaleLowerCase().includes(query.value.toLocaleLowerCase())&&(categoria.value==='Todos'||t.categoria===categoria.value)&&(status.value==='Todos'||t.estado===status.value)))
const stats=computed(()=>[{label:'Tickets abiertos',value:store.data.tickets.filter(t=>t.estado!=='Resuelta'&&t.estado!=='Rechazada').length,icon:'pi-ticket'},{label:'En proceso',value:store.data.tickets.filter(t=>t.estado==='En proceso').length,icon:'pi-code'},{label:'Necesitamos información',value:store.data.tickets.filter(t=>t.estado==='Necesitamos información').length,icon:'pi-check-square'},{label:'Resueltos',value:store.data.tickets.filter(t=>t.estado==='Resuelta').length,icon:'pi-check-circle'}])
const ticketEvents=computed(()=>store.data.activities.filter(e=>e.ticketId===selectedId.value))
const severity=(s:string)=>s==='Resuelta'?'success':s==='Necesitamos información'?'secondary':s==='En proceso'?'warn':'info'
const date=(s:string)=>new Date(s).toLocaleString('es-MX',{dateStyle:'medium',timeStyle:'short'})
async function run(action:()=>Promise<void>){busy.value=true;try{await action();toast.add({severity:'success',summary:'Guardado',life:2200})}catch(e){toast.add({severity:'error',summary:'No se pudo guardar',detail:e instanceof Error?e.message:'Intenta de nuevo',life:6000})}finally{busy.value=false}}
async function saveNote(){if(!note.value.trim()||!selected.value)return;await run(async()=>{await store.addActivity({ticketId:selectedId.value,text:note.value.trim(),visibility:visibility.value});note.value=''})}
async function saveGeneral(){if(!general.value.trim())return;await run(async()=>{await store.addActivity({ticketId:null,text:general.value.trim(),visibility:'Nota interna'});general.value='';generalOpen.value=false})}
function changeStatus(value:Status){if(selected.value&&value!==selected.value.estado)void run(()=>store.changeStatus(selected.value!.id,value))}
onMounted(()=>store.load())
</script>
<template><div class="page"><div class="page-heading"><div><h1>Tecnología</h1><p>Un espacio para reportar, resolver y dejar constancia.</p></div><Button label="Nueva solicitud" icon="pi pi-plus" :disabled="!store.ready||busy" @click="router.push('/tecnologia/solicitudes/nueva')"/></div>
<Message v-if="store.error" severity="error" :closable="false">{{ store.error }} <Button label="Reintentar" text @click="store.load()"/></Message>
<div class="stats"><div v-for="stat in stats" :key="stat.label" class="stat"><span>{{stat.label}} <i :class="['pi',stat.icon]"/></span><b>{{stat.value}}</b></div></div>
<div class="tabs"><RouterLink to="/tecnologia/tickets">Tickets</RouterLink><RouterLink to="/tecnologia/tablero">Tablero de trabajo</RouterLink><RouterLink to="/tecnologia/bitacora">Bitácora general</RouterLink></div>
<p v-if="store.loading" role="status">Cargando…</p>
<div v-else-if="section==='tickets'" class="tickets-layout"><section class="panel"><div class="panel-heading"><h2>Bandeja de tickets</h2><small>{{filtered.length}} solicitudes</small></div><div class="filters"><InputText v-model="query" aria-label="Buscar tickets" placeholder="Buscar por título, folio o solicitante"/><Select v-model="categoria" :options="['Todos',...categorias]" aria-label="Categoría"/><Select v-model="status" :options="['Todos',...statuses]" aria-label="Estado"/></div><div class="table-scroll"><table><thead><tr><th>Ticket / solicitud</th><th>Categoría</th><th>Estado</th></tr></thead><tbody><tr v-for="ticket in filtered" :key="ticket.id"><td><button class="ticket-link" @click="selectedId=ticket.id"><small>{{ticket.id.slice(0,14)}} · {{ticket.categoria}}</small><strong>{{ticket.title}}</strong><small>{{ticket.solicitanteId}} · {{ticket.responsableId ?? 'Sin responsable'}}</small></button></td><td><Tag :value="ticket.categoria" severity="secondary"/></td><td><Tag :value="ticket.estado" :severity="severity(ticket.estado)"/></td></tr><tr v-if="!filtered.length"><td colspan="3" class="empty">No hay tickets para mostrar.</td></tr></tbody></table></div></section><aside class="panel activity-panel"><div class="panel-heading"><h2>Actividad reciente</h2><i class="pi pi-history"/></div><div class="timeline"><article v-for="event in store.data.activities.slice(0,5)" :key="event.id"><small>{{event.ticketId?.slice(0,14)||'Actividad general'}}</small><p>{{event.text}}</p><small>{{date(event.createdAt)}} · {{event.visibility}}</small></article><p v-if="!store.data.activities.length">Aún no hay actividades.</p></div></aside></div>
<div v-else-if="section==='tablero'" class="board"><section v-for="column in statuses" :key="column" class="board-column"><h2>{{column}} <small>{{store.data.tickets.filter(t=>t.estado===column).length}}</small></h2><button v-for="ticket in store.data.tickets.filter(t=>t.estado===column)" :key="ticket.id" class="board-card" @click="selectedId=ticket.id"><small>{{ticket.categoria}} · {{ticket.id.slice(0,14)}}</small><strong>{{ticket.title}}</strong><p>{{ticket.responsableId ?? 'Sin responsable'}}</p></button><p v-if="!store.data.tickets.some(t=>t.estado===column)" class="empty">Sin tickets</p></section></div>
<section v-else class="panel"><div class="panel-heading"><div><h2>Bitácora general</h2><small>Avances, cambios de estado y actividades del equipo.</small></div><Button label="Registrar actividad" icon="pi pi-plus" :disabled="!store.ready||busy" @click="generalOpen=true"/></div><div class="timeline"><article v-for="event in store.data.activities" :key="event.id"><button v-if="event.ticketId" class="text-link" @click="selectedId=event.ticketId">{{event.ticketId.slice(0,14)}}</button><b v-else>Actividad general</b><p>{{event.text}}</p><small>{{date(event.createdAt)}} · {{event.visibility}}</small></article><p v-if="!store.data.activities.length" class="empty">Registra la primera actividad del equipo.</p></div></section>

<Dialog v-model:visible="detailOpen" modal :header="selected?.id.slice(0,14)" :style="{width:'740px'}" :breakpoints="{'780px':'95vw'}"><template v-if="selected"><h2>{{selected.title}}</h2><p class="description">{{selected.description}}</p><div class="detail-meta"><Tag :value="selected.categoria" severity="secondary"/><span>{{selected.solicitanteId}} · {{selected.responsableId ?? 'Sin responsable'}}</span></div><label for="ticket-status">Estado</label><Select inputId="ticket-status" :modelValue="selected.estado" :options="[...statuses]" :disabled="busy" @update:modelValue="changeStatus"/><h3>Bitácora del ticket</h3><div class="timeline"><article v-for="event in ticketEvents" :key="event.id"><p>{{event.text}}</p><small>{{date(event.createdAt)}} · {{event.visibility}}</small></article></div><form @submit.prevent="saveNote"><label for="note">Registrar avance o respuesta</label><Textarea id="note" v-model="note" required rows="3" maxlength="10000"/><label for="visibility">Visibilidad prevista</label><Select inputId="visibility" v-model="visibility" :options="['Nota interna','Respuesta al solicitante']"/><small class="hint">Clasificación para el futuro portal de clientes. Esta versión muestra la vista interna.</small><div class="actions"><Button type="submit" label="Guardar actividad" :loading="busy"/></div></form></template></Dialog>
<Dialog v-model:visible="generalOpen" modal header="Registrar actividad general" :style="{width:'560px'}" :breakpoints="{'600px':'95vw'}"><form @submit.prevent="saveGeneral"><label for="general">Actividad realizada</label><Textarea id="general" v-model="general" required rows="5" maxlength="10000" placeholder="Mantenimiento, revisión de equipos, actualización…"/><p>Se guardará como nota interna sin vincularla a un ticket.</p><div class="actions"><Button type="submit" label="Guardar actividad" :loading="busy"/></div></form></Dialog>
</div></template>
