<Project Sdk="Microsoft.NET.Sdk.Web"><PropertyGroup><TargetFramework>net9.0</TargetFramework><Nullable>enable</Nullable><ImplicitUsings>enable</ImplicitUsings></PropertyGroup><ItemGroup><ProjectReference Include="../Tecnologia.Application/Tecnologia.Application.csproj" /><ProjectReference Include="../Tecnologia.Infrastructure/Tecnologia.Infrastructure.csproj" /><ProjectReference Include="../../../shared/Tecnologia.Shared/Tecnologia.Shared.csproj" /></ItemGroup></Project>
